-- CREATE TABLES

CREATE TABLE userInfo (
	NAME VARCHAR(100) NULL DEFAULT "",
	AGE INT(11) NULL DEFAULT NULL,
	COUNTRY TEXT NULL DEFAULT NULL
)
COMMENT "User date info"
COLLATE "utf8_general_ci"
ENGINE=INNODB
;

CREATE TABLE problemsInfo (
	NAMESPROBLEMS VARCHAR(100) NULL DEFAULT "",
	DESKRIPTIONPROBLEM TEXT NULL DEFAULT NULL
)
COMMENT="problem information"
COLLATE="utf8_general_ci"
ENGINE=InnoDB
;

CREATE TABLE programmingDate (
	NAMELANGUAGE VARCHAR(100) NULL DEFAULT '',
	YEARSEXPERIENCE SMALLINT(11) NULL DEFAULT NULL,
	YEARSTART TINYINT(11) NULL DEFAULT NULL
)
COMMENT="information about the programming language"
COLLATE="utf8_general_ci"
ENGINE=InnoDB
;

-- INSERT

INSERT INTO userinfo (NAME, AGE, COUNTRY) VALUES ("ALEX", 25, "Ukraine");
INSERT INTO programmingdate (NAMELANGUAGE) VALUES ("JavaScript");
INSERT INTO programmingdate (YEARSEXPERIENCE) VALUES (1);
INSERT INTO programmingdate (YEARSTART) VALUES (22);
INSERT INTO problemsinfo (NAMESPROBLEMS, DESKRIPTIONPROBLEM) VALUES ("screen breakage", "the screen is cracked and does not work");