-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 16:05:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zarits_db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zarits_db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zarits_db1` DEFAULT CHARACTER SET utf8 ;
USE `zarits_db1` ;

-- -----------------------------------------------------
-- Table `zarits_db1`.`viewers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zarits_db1`.`viewers` (
  `idvw` INT NOT NULL AUTO_INCREMENT,
  `vw_name` VARCHAR(45) NOT NULL,
  `vw_age` INT NOT NULL,
  PRIMARY KEY (`idvw`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarits_db1`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zarits_db1`.`films` (
  `idfm` INT NOT NULL AUTO_INCREMENT,
  `fm_name` VARCHAR(45) NOT NULL,
  `fm_rating` INT NOT NULL,
  PRIMARY KEY (`idfm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarits_db1`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zarits_db1`.`directors` (
  `iddir` INT NOT NULL AUTO_INCREMENT,
  `dir_name` VARCHAR(45) NOT NULL,
  `id_suname` VARCHAR(45) NOT NULL,
  `dir_city` VARCHAR(45) NOT NULL,
  `dir_age` INT NOT NULL,
  PRIMARY KEY (`iddir`))
ENGINE = InnoDB;

INSERT INTO films 
VALUES (1, "Tenet", 8),
(2, "Schindler's List", 9),
(3, "Pulp Fiction", 9),
(4, "Avatar", 8),
(5, "Star Wars: Episode IV - A New Hope", 9);

INSERT INTO viewers 
VALUES (1, "Ivan228", 13),
(2, "OlehMaxno", 23),
(3, "Bondageman", 19),
(4, "Alezx", 18),
(5, "pan_mykhailo", 59);

INSERT INTO  directors
VALUES (1, "Christopher", "Nolan", "London", 51),
(2, "Quentin", "Tarantino", "Knoxville", 59),
(3, "George", "Lucas", "Modesto", 78),
(4, "Steven", "Spielberg", "Cincinnati", 75),
(5, "James", "Cameron", "Kapuskasing", 67);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
